/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;


import classe.Utilisateur;
import dao.UtilisateurDAO;
import static java.awt.image.ImageObserver.ABORT;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author halid
 */
public class PanelUtilisateur extends javax.swing.JPanel {

    /**
     * Creates new form PanelUtilisateur
     */
    public PanelUtilisateur() {
        initComponents();
        vider_utilisateur();
        liste_utilisateur();
       //  Scroll.setVerticalScrollBar(new ScrollBarCustom());
        //Scroll.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel24 = new javax.swing.JPanel();
        txt_nom3 = new textfield_suggestion.TextFieldSuggestion();
        jLabel66 = new javax.swing.JLabel();
        txt_login = new textfield_suggestion.TextFieldSuggestion();
        jLabel67 = new javax.swing.JLabel();
        txt_password = new textfield_suggestion.TextFieldSuggestion();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        txt_profil = new combo_suggestion.ComboBoxSuggestion();
        Scroll = new javax.swing.JScrollPane();
        tb_utilisateur = new rojeru_san.complementos.RSTableMetro();
        btn_enregistrer5 = new com.raven.swing.Button();
        btn_supprimer5 = new com.raven.swing.Button();
        btn_modifier5 = new com.raven.swing.Button();
        btn_imprimer5 = new com.raven.swing.Button();
        jLabel70 = new javax.swing.JLabel();

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setPreferredSize(new java.awt.Dimension(1240, 890));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nom3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_nom3.setRound(0);
        txt_nom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nom3ActionPerformed(evt);
            }
        });
        jPanel24.add(txt_nom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 640, 40));

        jLabel66.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel66.setText("Nom");
        jPanel24.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        txt_login.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_login.setRound(0);
        txt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loginActionPerformed(evt);
            }
        });
        jPanel24.add(txt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 640, 40));

        jLabel67.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel67.setText("Login");
        jPanel24.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        txt_password.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_password.setRound(0);
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        jPanel24.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 640, 40));

        jLabel68.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel68.setText("Password");
        jPanel24.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel69.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel69.setText("Profil");
        jPanel24.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        txt_profil.setEditable(false);
        txt_profil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrateur", "Utilisateur" }));
        txt_profil.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_profilActionPerformed(evt);
            }
        });
        jPanel24.add(txt_profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 640, 40));

        tb_utilisateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nom", "Login", "Password", "Profil"
            }
        ));
        tb_utilisateur.setColorBackgoundHead(new java.awt.Color(153, 153, 255));
        tb_utilisateur.setColorBordeFilas(new java.awt.Color(153, 153, 255));
        tb_utilisateur.setColorBordeHead(new java.awt.Color(153, 153, 255));
        tb_utilisateur.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tb_utilisateur.setColorFilasForeground1(new java.awt.Color(153, 153, 255));
        tb_utilisateur.setColorFilasForeground2(new java.awt.Color(153, 153, 255));
        tb_utilisateur.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        tb_utilisateur.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        tb_utilisateur.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        tb_utilisateur.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        tb_utilisateur.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        tb_utilisateur.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tb_utilisateur.setRowHeight(40);
        tb_utilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_utilisateurMouseClicked(evt);
            }
        });
        Scroll.setViewportView(tb_utilisateur);

        jPanel24.add(Scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 472, 1170, 390));

        btn_enregistrer5.setBackground(new java.awt.Color(51, 51, 255));
        btn_enregistrer5.setForeground(new java.awt.Color(255, 255, 255));
        btn_enregistrer5.setText("Enregistrer");
        btn_enregistrer5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_enregistrer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrer5ActionPerformed(evt);
            }
        });
        jPanel24.add(btn_enregistrer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 150, 45));

        btn_supprimer5.setBackground(new java.awt.Color(255, 51, 51));
        btn_supprimer5.setForeground(new java.awt.Color(255, 255, 255));
        btn_supprimer5.setText("Supprimer");
        btn_supprimer5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_supprimer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimer5ActionPerformed(evt);
            }
        });
        jPanel24.add(btn_supprimer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 150, 45));

        btn_modifier5.setBackground(new java.awt.Color(255, 204, 51));
        btn_modifier5.setForeground(new java.awt.Color(255, 255, 255));
        btn_modifier5.setText("Modifier");
        btn_modifier5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_modifier5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier5ActionPerformed(evt);
            }
        });
        jPanel24.add(btn_modifier5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 150, 45));

        btn_imprimer5.setBackground(new java.awt.Color(51, 204, 0));
        btn_imprimer5.setForeground(new java.awt.Color(255, 255, 255));
        btn_imprimer5.setText("Imprimer");
        btn_imprimer5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_imprimer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimer5ActionPerformed(evt);
            }
        });
        jPanel24.add(btn_imprimer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 150, 45));

        jLabel70.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(0, 51, 255));
        jLabel70.setText("Gestion des Utilisateurs");
        jPanel24.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nom3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nom3ActionPerformed

    private void txt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loginActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_profilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_profilActionPerformed

    private void tb_utilisateurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_utilisateurMouseClicked
        int index = tb_utilisateur.getSelectedRow();
        if (index!=-1){
            int id = (int)tb_utilisateur.getValueAt(index,0);
            UtilisateurDAO udao = new UtilisateurDAO();
            Utilisateur etu = udao.recherche(id);
            txt_nom3.setText(etu.getNom());
            txt_login.setText(etu.getLogin());
            txt_password.setText(etu.getPassword());
            txt_profil.setSelectedItem(etu.getProfil());
        }
    }//GEN-LAST:event_tb_utilisateurMouseClicked

    private void btn_enregistrer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrer5ActionPerformed
        UtilisateurDAO udao = new UtilisateurDAO();
        String nom = txt_nom3.getText();
        String login = txt_login.getText();
        String password = txt_password.getText();
        String profil = txt_profil.getSelectedItem().toString();
        if (nom.equals("") || login.equals("") || password.equals("") || profil.equals("") ) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner tous les champs ");
        } else {
            Utilisateur ut = new Utilisateur(nom, login, password,profil);
            udao.inserer(ut);
            vider_utilisateur();
            liste_utilisateur();
        }
    }//GEN-LAST:event_btn_enregistrer5ActionPerformed

    private void btn_supprimer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimer5ActionPerformed
        int index = tb_utilisateur.getSelectedRow();
        if (index==-1){
            JOptionPane.showMessageDialog(this,"Veuillez selectionnez une ligne");
        }
        else {
            int id = (int)tb_utilisateur.getValueAt(index,0);
            UtilisateurDAO udao = new UtilisateurDAO();
            udao.supprimer(id);
            vider_utilisateur();
            liste_utilisateur();

        }
    }//GEN-LAST:event_btn_supprimer5ActionPerformed

    private void btn_modifier5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier5ActionPerformed
        UtilisateurDAO udao = new UtilisateurDAO();
        String nom = txt_nom3.getText();
        String login = txt_login.getText();
        String password = txt_password.getText();
        String profil = txt_profil.getSelectedItem().toString();
        if (nom.equals("") || login.equals("") || password.equals("") || profil.equals("")) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner tous les champs ");
        } else {
            int index = tb_utilisateur.getSelectedRow();
            int id = (int)tb_utilisateur.getValueAt(index,0);
            Utilisateur ut = new Utilisateur(nom, login, password,profil);
            udao.modifier(ut, id);
            vider_utilisateur();
            liste_utilisateur();
        }
    }//GEN-LAST:event_btn_modifier5ActionPerformed
         private void liste_utilisateur() {
        UtilisateurDAO udao = new UtilisateurDAO();
        List<Utilisateur> utilisateur = udao.liste();
        for (int i = 0; i < utilisateur.size(); i++) {
            ((DefaultTableModel) tb_utilisateur.getModel()).addRow(new Object[]{
                utilisateur.get(i).getIdu(),
                utilisateur.get(i).getNom(),
                utilisateur.get(i).getLogin(),
                utilisateur.get(i).getPassword(),
                utilisateur.get(i).getProfil(),
            });
        }

    }
  private void vider_utilisateur() {
        txt_nom3.setText("");
        txt_login.setText("");
        txt_password.setText("");
        txt_profil.setSelectedItem(ABORT);
        DefaultTableModel model = (DefaultTableModel) tb_utilisateur.getModel();
        int n = model.getRowCount();
        for (int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
        }
    }
    private void btn_imprimer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimer5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imprimer5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scroll;
    private com.raven.swing.Button btn_enregistrer5;
    private com.raven.swing.Button btn_imprimer5;
    private com.raven.swing.Button btn_modifier5;
    private com.raven.swing.Button btn_supprimer5;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JPanel jPanel24;
    private rojeru_san.complementos.RSTableMetro tb_utilisateur;
    private textfield_suggestion.TextFieldSuggestion txt_login;
    private textfield_suggestion.TextFieldSuggestion txt_nom3;
    private textfield_suggestion.TextFieldSuggestion txt_password;
    private combo_suggestion.ComboBoxSuggestion txt_profil;
    // End of variables declaration//GEN-END:variables
}
