/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import classe.Car;
import classe.Chauffeur;
import classe.Voyage;
import dao.CarDAO;
import dao.ChauffeurDAO;
import dao.Connectdb;
import dao.VoyageDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author halid
 */
public class PanelChauffeur extends javax.swing.JPanel {
boolean modifier ;
    /**
     * Creates new form PanelChauffeur
     */
    public PanelChauffeur() {
        initComponents();
        viderChauffeur();
        liste_chauffeur();
        combo_car();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChauffeurAjouter = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txt_nom2 = new textfield_suggestion.TextFieldSuggestion();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        btn_enregistrer45 = new com.raven.swing.Button();
        btn_supprimer45 = new com.raven.swing.Button();
        txt_salaire = new textfield_suggestion.TextFieldSuggestion();
        txt_cni2 = new textfield_suggestion.TextFieldSuggestion();
        txt_adresse1 = new textfield_suggestion.TextFieldSuggestion();
        txt_date2 = new com.toedter.calendar.JDateChooser();
        jLabel43 = new javax.swing.JLabel();
        txt_car11 = new combo_suggestion.ComboBoxSuggestion();
        txt_taille = new textfield_suggestion.TextFieldSuggestion();
        txt_marque = new textfield_suggestion.TextFieldSuggestion();
        txt_matricule = new textfield_suggestion.TextFieldSuggestion();
        jPanel21 = new javax.swing.JPanel();
        Scroll = new javax.swing.JScrollPane();
        tb_chauffeur = new rojeru_san.complementos.RSTableMetro();
        btn_enregistrer2 = new com.raven.swing.Button();
        btn_supprimer2 = new com.raven.swing.Button();
        btn_modifier2 = new com.raven.swing.Button();
        btn_imprimer2 = new com.raven.swing.Button();
        jLabel57 = new javax.swing.JLabel();

        ChauffeurAjouter.setUndecorated(true);
        ChauffeurAjouter.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fiche Voyage");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 50));

        ChauffeurAjouter.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel37.setText("Adresse");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel41.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel41.setText("Nom");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel42.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel42.setText("Cni");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        txt_nom2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_nom2.setRound(0);
        txt_nom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nom2ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_nom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 460, 40));

        jLabel38.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel38.setText("Date embauche");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, 30));

        jLabel40.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel40.setText("Salaire");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 30));

        btn_enregistrer45.setBackground(new java.awt.Color(51, 51, 255));
        btn_enregistrer45.setForeground(new java.awt.Color(255, 255, 255));
        btn_enregistrer45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/valid-vector-icon-png_267488.png"))); // NOI18N
        btn_enregistrer45.setText("  Terminer");
        btn_enregistrer45.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        btn_enregistrer45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrer45ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_enregistrer45, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 150, 45));

        btn_supprimer45.setBackground(new java.awt.Color(255, 51, 51));
        btn_supprimer45.setForeground(new java.awt.Color(255, 255, 255));
        btn_supprimer45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/anull-vector-icon-png_267488.png"))); // NOI18N
        btn_supprimer45.setText("  Annuler");
        btn_supprimer45.setToolTipText("");
        btn_supprimer45.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        btn_supprimer45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimer45ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_supprimer45, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, 150, 45));

        txt_salaire.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_salaire.setRound(0);
        txt_salaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salaireActionPerformed(evt);
            }
        });
        jPanel2.add(txt_salaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 460, 40));

        txt_cni2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_cni2.setRound(0);
        txt_cni2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cni2ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_cni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 460, 40));

        txt_adresse1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_adresse1.setRound(0);
        txt_adresse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_adresse1ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_adresse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 460, 40));

        txt_date2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txt_date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 460, 40));

        jLabel43.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel43.setText("Car");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        txt_car11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_car11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_car11ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_car11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 70, 40));

        txt_taille.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_taille.setRound(0);
        txt_taille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tailleActionPerformed(evt);
            }
        });
        jPanel2.add(txt_taille, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 120, 40));

        txt_marque.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_marque.setRound(0);
        txt_marque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_marqueActionPerformed(evt);
            }
        });
        jPanel2.add(txt_marque, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 120, 40));

        txt_matricule.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_matricule.setRound(0);
        txt_matricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matriculeActionPerformed(evt);
            }
        });
        jPanel2.add(txt_matricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 120, 40));

        ChauffeurAjouter.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 550, 700));

        setMinimumSize(new java.awt.Dimension(1240, 890));
        setPreferredSize(new java.awt.Dimension(1240, 890));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setMinimumSize(new java.awt.Dimension(1240, 890));
        jPanel21.setPreferredSize(new java.awt.Dimension(1240, 890));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_chauffeur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nom", "Adresse", "Cni", "Salaire", "Car", "Date Embauche", "Statut"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_chauffeur.setColorBackgoundHead(new java.awt.Color(153, 153, 255));
        tb_chauffeur.setColorBordeFilas(new java.awt.Color(153, 153, 255));
        tb_chauffeur.setColorBordeHead(new java.awt.Color(153, 153, 255));
        tb_chauffeur.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tb_chauffeur.setColorFilasForeground1(new java.awt.Color(153, 153, 255));
        tb_chauffeur.setColorFilasForeground2(new java.awt.Color(153, 153, 255));
        tb_chauffeur.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        tb_chauffeur.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        tb_chauffeur.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        tb_chauffeur.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        tb_chauffeur.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        tb_chauffeur.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tb_chauffeur.setRowHeight(40);
        tb_chauffeur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_chauffeurMouseClicked(evt);
            }
        });
        Scroll.setViewportView(tb_chauffeur);

        jPanel21.add(Scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 152, 1170, 710));

        btn_enregistrer2.setBackground(new java.awt.Color(51, 51, 255));
        btn_enregistrer2.setForeground(new java.awt.Color(255, 255, 255));
        btn_enregistrer2.setText("Enregistrer");
        btn_enregistrer2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_enregistrer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrer2ActionPerformed(evt);
            }
        });
        jPanel21.add(btn_enregistrer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, 45));

        btn_supprimer2.setBackground(new java.awt.Color(255, 51, 51));
        btn_supprimer2.setForeground(new java.awt.Color(255, 255, 255));
        btn_supprimer2.setText("Supprimer");
        btn_supprimer2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_supprimer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimer2ActionPerformed(evt);
            }
        });
        jPanel21.add(btn_supprimer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 150, 45));

        btn_modifier2.setBackground(new java.awt.Color(255, 204, 51));
        btn_modifier2.setForeground(new java.awt.Color(255, 255, 255));
        btn_modifier2.setText("Modifier");
        btn_modifier2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_modifier2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier2ActionPerformed(evt);
            }
        });
        jPanel21.add(btn_modifier2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 150, 45));

        btn_imprimer2.setBackground(new java.awt.Color(51, 204, 0));
        btn_imprimer2.setForeground(new java.awt.Color(255, 255, 255));
        btn_imprimer2.setText("Imprimer");
        btn_imprimer2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_imprimer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimer2ActionPerformed(evt);
            }
        });
        jPanel21.add(btn_imprimer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, 150, 45));

        jLabel57.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 51, 255));
        jLabel57.setText("Gestion des Chauffeurs");
        jPanel21.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 1250, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void tb_chauffeurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_chauffeurMouseClicked
        int index = tb_chauffeur.getSelectedRow();
        if (index!=-1){
            int id = (int)tb_chauffeur.getValueAt(index,0);
            ChauffeurDAO edao = new ChauffeurDAO();
            Chauffeur etu = edao.recherche(id);
            txt_nom2.setText(etu.getNom());
            txt_adresse1.setText(etu.getAdresse());
            txt_cni2.setText(etu.getCni());
            txt_salaire.setText(etu.getSalaire()+"");
            txt_car11.setSelectedItem(etu.getCar()+"");
            txt_date2.setDate(etu.getDate_enreg());
         
        }
    }//GEN-LAST:event_tb_chauffeurMouseClicked

    private void btn_enregistrer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrer2ActionPerformed
         ChauffeurAjouter.setVisible(true);
         modifier=false;
          ChauffeurAjouter.pack();
        ChauffeurAjouter.setLocationRelativeTo(null);
        ChauffeurAjouter.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       
        txt_nom2.setText("");
        txt_adresse1.setText("");
        txt_cni2.setText("");
        txt_salaire.setText("");
        
        txt_date2.setDate(null);
        
        /*        ChauffeurDAO edao = new ChauffeurDAO();
        String nom = txt_nom2.getText();
        String adresse = txt_adresse1.getText();
        String cni = txt_cni2.getText();
        String salaire = txt_salaire.getText();
        Date date = txt_date2.getDate();
        if (nom.equals("") || adresse.equals("") || cni.equals("")|| salaire.equals("")|| date == null) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner tous les champs ");
        } else {
            Chauffeur et = new Chauffeur(nom, adresse, cni, Integer.parseInt(salaire), date);
            edao.inserer(et);
            viderChauffeur();
            liste_chauffeur();
        }*/
    }//GEN-LAST:event_btn_enregistrer2ActionPerformed

    private void btn_supprimer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimer2ActionPerformed
        int index = tb_chauffeur.getSelectedRow();
        if (index==-1){
            JOptionPane.showMessageDialog(this,"Veuillez selectionnez une ligne");
        }
        else {
            int id = (int)tb_chauffeur.getValueAt(index,0);
            ChauffeurDAO edao = new ChauffeurDAO();
            edao.supprimer(id);
            viderChauffeur();
            liste_chauffeur();

        }
    }//GEN-LAST:event_btn_supprimer2ActionPerformed

    private void btn_modifier2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier2ActionPerformed
        int index = tb_chauffeur.getSelectedRow();
        if (index==-1){
            JOptionPane.showMessageDialog(this,"Veuillez selectionnez un client");
        }
        else {
        
        ChauffeurAjouter.setVisible(true);
        ChauffeurAjouter.pack();
        ChauffeurAjouter.setLocationRelativeTo(null);
        ChauffeurAjouter.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        modifier=true;
          int indexx = tb_chauffeur.getSelectedRow();
        if (indexx!=-1){
            int id = (int)tb_chauffeur.getValueAt(index,0);
            ChauffeurDAO edao = new ChauffeurDAO();
            Chauffeur etu = edao.recherche(id);
            txt_nom2.setText(etu.getNom());
            txt_adresse1.setText(etu.getAdresse());
            txt_cni2.setText(etu.getCni());
            txt_salaire.setText(etu.getSalaire()+"");
            txt_car11.setSelectedItem(etu.getCar()+"");
            txt_date2.setDate(etu.getDate_enreg());
           
        }
        }
        /*        ChauffeurDAO edao = new ChauffeurDAO();
        String nom = txt_nom2.getText();
        String adresse = txt_adresse1.getText();
        String cni = txt_cni2.getText();
        String salaire = txt_salaire.getText();
        Date date = txt_date2.getDate();
        if (nom.equals("") || adresse.equals("") || cni.equals("")|| salaire.equals("")|| date == null) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner tous les champs ");
        }  else {
            int index = tb_chauffeur.getSelectedRow();
            int id = (int)tb_chauffeur.getValueAt(index,0);
            Chauffeur et = new Chauffeur(nom, adresse, cni, Integer.parseInt(salaire), date);
            edao.modifier(et, id);
            viderChauffeur();
            liste_chauffeur();
        }*/
    }//GEN-LAST:event_btn_modifier2ActionPerformed
        private void liste_chauffeur() {
        ChauffeurDAO edao = new ChauffeurDAO();
        List<Chauffeur> chauffeur = edao.liste();
        for (int i = 0; i < chauffeur.size(); i++) {
            ((DefaultTableModel) tb_chauffeur.getModel()).addRow(new Object[]{
                chauffeur.get(i).getIdchauf(),
                chauffeur.get(i).getNom(),
                chauffeur.get(i).getAdresse(),
                chauffeur.get(i).getCni(),
                chauffeur.get(i).getSalaire(),
                chauffeur.get(i).getCar(),
                chauffeur.get(i).getDate_enreg(),
                chauffeur.get(i).getStatut()
            });
        }

    }
   private void combo_car() {
        CarDAO cdao = new CarDAO();
        List <Car> carr = cdao.liste();
        for (int i = 0; i < carr.size(); i++) {
            txt_car11.addItem(carr.get(i).getIdcar()+"");
        }

    }
    private void viderChauffeur() {
        txt_nom2.setText("");
        txt_adresse1.setText("");
        txt_cni2.setText("");
        txt_salaire.setText("");
        
        txt_date2.setDate(null);
        
        DefaultTableModel model = (DefaultTableModel) tb_chauffeur.getModel();
        int n = model.getRowCount();
        for (int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
        }
        
    }
    private void btn_imprimer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imprimer2ActionPerformed

    private void txt_nom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nom2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nom2ActionPerformed

    private void btn_enregistrer45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrer45ActionPerformed
        ChauffeurDAO edao = new ChauffeurDAO();
        String nom = txt_nom2.getText();
        String adresse = txt_adresse1.getText();
        String cni = txt_cni2.getText();
        String salaire = txt_salaire.getText();
        String car = txt_car11.getSelectedItem().toString();
        Date date = txt_date2.getDate();
        String statut = "Disponible";
        if (nom.equals("") || adresse.equals("") || cni.equals("")|| salaire.equals("")|| car.equals("")|| date == null|| statut.equals("")) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner tous les champs ");
        } else if(modifier==false){

            Chauffeur et = new Chauffeur(nom, adresse, cni, Integer.parseInt(salaire),car, date,statut);
            edao.inserer(et);
            viderChauffeur();
            liste_chauffeur();
            ChauffeurAjouter.setVisible(false);
        }
        else if(modifier==true){
            int index = tb_chauffeur.getSelectedRow();
            int id = (int)tb_chauffeur.getValueAt(index,0);
             Chauffeur et = new Chauffeur(nom, adresse, cni, Integer.parseInt(salaire),car, date,statut);
            edao.modifier(et, id);
            viderChauffeur();
            liste_chauffeur();
            ChauffeurAjouter.setVisible(false);
        }

        //VoyageAjouter.dispose();
    }//GEN-LAST:event_btn_enregistrer45ActionPerformed

    private void btn_supprimer45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimer45ActionPerformed
        ChauffeurAjouter.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_supprimer45ActionPerformed

    private void txt_salaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_salaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_salaireActionPerformed

    private void txt_cni2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cni2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cni2ActionPerformed

    private void txt_adresse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_adresse1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_adresse1ActionPerformed

    private void txt_tailleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tailleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tailleActionPerformed

    private void txt_marqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_marqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marqueActionPerformed

    private void txt_matriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matriculeActionPerformed

    private void txt_car11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_car11ActionPerformed
       CarDAO cdao = new CarDAO();
        List <Car> car = cdao.liste();

        int i = txt_car11.getSelectedIndex();
        txt_taille.setText(car.get(i).getStatut()+"");
        txt_matricule.setText(car.get(i).getNb_place()+"");
        txt_marque.setText(car.get(i).getMarque()+"");
    }//GEN-LAST:event_txt_car11ActionPerformed

public void Statut_chauffeur(){
      VoyageDAO vdao = new VoyageDAO();
        List<Voyage> voyage = vdao.liste();
         Date today = new Date();
        today.setHours(0);
        today.setMinutes(0);
        today.setSeconds(0);
         for (int i = 0; i < voyage.size(); i++) {
            
            //Voyage voy=vdao.recherche(voyage.get(i).getDepart());
            Date depart=voyage.get(i).getDepart();
            Date arrive=voyage.get(i).getArrive();
            
            if(depart.compareTo(today) < 0 && arrive.compareTo(today) > 0){
            
             try {
            Connection con = Connectdb.getInstance();
            String sql = "UPDATE chauffeur INNER JOIN voyage ON chauffeur.idchauf = voyage.idchauf SET chauffeur.statut='Indisponible' WHERE voyage.depart < DATE( NOW() ) and voyage.arrive >DATE( NOW() );";
            //String sql = "update issue_book_details set status = ? where student_id = ? and book_id = ? and status = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.executeUpdate();
           int rowCount =  pst.executeUpdate();
        } catch (SQLException e) {
        }
           }
            else if(arrive.compareTo(today) < 0){
                 try {
            Connection con = Connectdb.getInstance();
            String sql = "UPDATE chauffeur INNER JOIN voyage ON chauffeur.idchauf = voyage.idchauf SET chauffeur.statut='Disponible' WHERE  voyage.arrive <DATE( NOW() );";
            //String sql = "update issue_book_details set status = ? where student_id = ? and book_id = ? and status = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.executeUpdate();
           int rowCount =  pst.executeUpdate();
        } catch (SQLException e) {
        }
            }
             else if(depart.compareTo(today) > 0){
                 try {
            Connection con = Connectdb.getInstance();
            String sql = "UPDATE chauffeur INNER JOIN voyage ON chauffeur.idchauf = voyage.idchauf SET chauffeur.statut='Reserver' WHERE  voyage.depart >DATE( NOW() );";
            //String sql = "update issue_book_details set status = ? where student_id = ? and book_id = ? and status = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.executeUpdate();
           int rowCount =  pst.executeUpdate();
        } catch (SQLException e) {
        }
            }
          }
        
        
      
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame ChauffeurAjouter;
    private javax.swing.JScrollPane Scroll;
    private com.raven.swing.Button btn_enregistrer2;
    private com.raven.swing.Button btn_enregistrer45;
    private com.raven.swing.Button btn_imprimer2;
    private com.raven.swing.Button btn_modifier2;
    private com.raven.swing.Button btn_supprimer2;
    private com.raven.swing.Button btn_supprimer45;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private rojeru_san.complementos.RSTableMetro tb_chauffeur;
    private textfield_suggestion.TextFieldSuggestion txt_adresse1;
    private combo_suggestion.ComboBoxSuggestion txt_car11;
    private textfield_suggestion.TextFieldSuggestion txt_cni2;
    private com.toedter.calendar.JDateChooser txt_date2;
    private textfield_suggestion.TextFieldSuggestion txt_marque;
    private textfield_suggestion.TextFieldSuggestion txt_matricule;
    private textfield_suggestion.TextFieldSuggestion txt_nom2;
    private textfield_suggestion.TextFieldSuggestion txt_salaire;
    private textfield_suggestion.TextFieldSuggestion txt_taille;
    // End of variables declaration//GEN-END:variables
}
