/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import classe.Client;
import classe.Ticket;
import classe.Voyage;
import dao.ClientDAO;
import dao.TicketDAO;
import dao.VoyageDAO;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author halid
 */
public class PanelTicket extends javax.swing.JPanel {

    /**
     * Creates new form PanelTicket
     */
    public PanelTicket() {
        initComponents();
        viderTicket();
        liste_ticket();
        combo_client();
        combo_voyage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel22 = new javax.swing.JPanel();
        txt_date = new com.toedter.calendar.JDateChooser();
        jScrollPane10 = new javax.swing.JScrollPane();
        tb_ticket = new rojeru_san.complementos.RSTableMetro();
        txt_destination = new textfield_suggestion.TextFieldSuggestion();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        txt_source = new textfield_suggestion.TextFieldSuggestion();
        jLabel60 = new javax.swing.JLabel();
        txt_nom = new textfield_suggestion.TextFieldSuggestion();
        jLabel61 = new javax.swing.JLabel();
        txt_cni = new textfield_suggestion.TextFieldSuggestion();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        txt_client = new combo_suggestion.ComboBoxSuggestion();
        txt_voyage = new combo_suggestion.ComboBoxSuggestion();
        btn_enregistrer = new com.raven.swing.Button();
        btn_supprimer = new com.raven.swing.Button();
        btn_modifier = new com.raven.swing.Button();
        btn_imprimer = new com.raven.swing.Button();
        jLabel65 = new javax.swing.JLabel();
        txt_prix = new textfield_suggestion.TextFieldSuggestion();
        jLabel66 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_date.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 380, 40));

        tb_ticket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Code Voyage", "Source", "Destination", "Code Client", "Nom", "Cni", "Date", "Prix"
            }
        ));
        tb_ticket.setColorBackgoundHead(new java.awt.Color(153, 153, 255));
        tb_ticket.setColorBordeFilas(new java.awt.Color(153, 153, 255));
        tb_ticket.setColorBordeHead(new java.awt.Color(153, 153, 255));
        tb_ticket.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tb_ticket.setColorFilasForeground1(new java.awt.Color(153, 153, 255));
        tb_ticket.setColorFilasForeground2(new java.awt.Color(153, 153, 255));
        tb_ticket.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        tb_ticket.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        tb_ticket.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        tb_ticket.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        tb_ticket.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        tb_ticket.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tb_ticket.setRowHeight(40);
        tb_ticket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_ticketMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(tb_ticket);

        jPanel22.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 1180, 270));

        txt_destination.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_destination.setRound(0);
        txt_destination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_destinationActionPerformed(evt);
            }
        });
        jPanel22.add(txt_destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 390, 40));

        jLabel58.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel58.setText("Code Client");
        jPanel22.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, -1, -1));

        jLabel59.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel59.setText("Destination");
        jPanel22.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        txt_source.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_source.setRound(0);
        txt_source.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sourceActionPerformed(evt);
            }
        });
        jPanel22.add(txt_source, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 390, 40));

        jLabel60.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel60.setText("Source");
        jPanel22.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        txt_nom.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_nom.setRound(0);
        txt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomActionPerformed(evt);
            }
        });
        jPanel22.add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 380, 40));

        jLabel61.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel61.setText("Nom");
        jPanel22.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, -1, -1));

        txt_cni.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_cni.setRound(0);
        txt_cni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cniActionPerformed(evt);
            }
        });
        jPanel22.add(txt_cni, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 380, 40));

        jLabel62.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel62.setText("Prix");
        jPanel22.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        jLabel63.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel63.setText("Code Voyage");
        jPanel22.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel64.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel64.setText("Date Achat");
        jPanel22.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, -1, -1));

        txt_client.setEditable(false);
        txt_client.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_clientActionPerformed(evt);
            }
        });
        jPanel22.add(txt_client, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 380, 40));

        txt_voyage.setEditable(false);
        txt_voyage.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_voyage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_voyageActionPerformed(evt);
            }
        });
        jPanel22.add(txt_voyage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 390, 40));

        btn_enregistrer.setBackground(new java.awt.Color(51, 51, 255));
        btn_enregistrer.setForeground(new java.awt.Color(255, 255, 255));
        btn_enregistrer.setText("Enregistrer");
        btn_enregistrer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrerActionPerformed(evt);
            }
        });
        jPanel22.add(btn_enregistrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 150, 45));

        btn_supprimer.setBackground(new java.awt.Color(255, 51, 51));
        btn_supprimer.setForeground(new java.awt.Color(255, 255, 255));
        btn_supprimer.setText("Supprimer");
        btn_supprimer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });
        jPanel22.add(btn_supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 150, 45));

        btn_modifier.setBackground(new java.awt.Color(255, 204, 51));
        btn_modifier.setForeground(new java.awt.Color(255, 255, 255));
        btn_modifier.setText("Modifier");
        btn_modifier.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });
        jPanel22.add(btn_modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 150, 45));

        btn_imprimer.setBackground(new java.awt.Color(51, 204, 0));
        btn_imprimer.setForeground(new java.awt.Color(255, 255, 255));
        btn_imprimer.setText("Imprimer");
        btn_imprimer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimerActionPerformed(evt);
            }
        });
        jPanel22.add(btn_imprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 150, 45));

        jLabel65.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(0, 51, 255));
        jLabel65.setText("Gestion des Tickets");
        jPanel22.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        txt_prix.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_prix.setRound(0);
        txt_prix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_prixActionPerformed(evt);
            }
        });
        jPanel22.add(txt_prix, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 390, 40));

        jLabel66.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel66.setText("Cni");
        jPanel22.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, -1, -1));

        add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 950));
    }// </editor-fold>//GEN-END:initComponents

    private void tb_ticketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_ticketMouseClicked
        int index = tb_ticket.getSelectedRow();
        if (index!=-1){
            int id = (int)tb_ticket.getValueAt(index,0);
            TicketDAO tdao = new TicketDAO();
            Ticket etu = tdao.recherche(id);
            txt_voyage.setSelectedItem(etu.getIdvoy()+"");
            txt_source.setText(etu.getSource());
            txt_destination.setText(etu.getDestination());
            txt_client.setSelectedItem(etu.getIdclt()+"");
            txt_nom.setText(etu.getNom());
            txt_cni.setText(etu.getCni());
            txt_date.setDate(etu.getDate());
            txt_prix.setText(etu.getPrix()+"");
        }
    }//GEN-LAST:event_tb_ticketMouseClicked

    private void txt_destinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_destinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_destinationActionPerformed

    private void txt_sourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sourceActionPerformed

    private void txt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomActionPerformed

    private void txt_cniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cniActionPerformed

    private void txt_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_clientActionPerformed
        ClientDAO cdao = new ClientDAO();
        List <Client> client = cdao.liste();

        int j = (int)txt_client.getSelectedIndex();
        txt_nom.setText(client.get(j).getNom()+"");
        txt_cni.setText(client.get(j).getCni()+"");
    }//GEN-LAST:event_txt_clientActionPerformed

    private void txt_voyageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_voyageActionPerformed
        VoyageDAO cdao = new VoyageDAO();
        List <Voyage> voyage = cdao.liste();

        int j = (int)txt_voyage.getSelectedIndex();
        txt_source.setText(voyage.get(j).getSource()+"");
        txt_destination.setText(voyage.get(j).getDestination()+"");
    }//GEN-LAST:event_txt_voyageActionPerformed

    private void btn_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrerActionPerformed
        TicketDAO tdao = new TicketDAO();
        String idvoy = txt_voyage.getSelectedItem().toString();
        String source = txt_source.getText();
        String destination = txt_destination.getText();
        String idclt = txt_client.getSelectedItem().toString();
        String nom = txt_nom.getText();
        String cni = txt_cni.getText();
        Date date = txt_date.getDate();
        String prix= txt_prix.getText();
        if (idvoy.equals("") ||idclt.equals("") ||nom.equals("") || cni.equals("") || date==null) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner tous les champs ");
        } else {
            Ticket ti = new Ticket(Integer.parseInt(idvoy),source,destination ,Integer.parseInt(idclt), nom, cni, date,Integer.parseInt(prix));
            tdao.inserer(ti);
            viderTicket();
            liste_ticket();
        }
    }//GEN-LAST:event_btn_enregistrerActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        int index = tb_ticket.getSelectedRow();
        if (index==-1){
            JOptionPane.showMessageDialog(this,"Veuillez selectionnez une ligne");
        }
        else {
            int id = (int)tb_ticket.getValueAt(index,0);
            TicketDAO tdao = new TicketDAO();
            tdao.supprimer(id);
            viderTicket();
            liste_ticket();

        }
    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
        TicketDAO tdao = new TicketDAO();
        String idvoy = txt_voyage.getSelectedItem().toString();
        String source = txt_source.getText();
        String destination = txt_destination.getText();
        String idclt = txt_client.getSelectedItem().toString();
        String nom = txt_nom.getText();
        String cni = txt_cni.getText();
        Date date = txt_date.getDate();
        String prix= txt_prix.getText();
        if (idvoy.equals("") ||idclt.equals("") ||nom.equals("") || cni.equals("") || date==null) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner tous les champs ");
        } else {
            int index = tb_ticket.getSelectedRow();
            int id = (int)tb_ticket.getValueAt(index,0);
            Ticket ti = new Ticket(Integer.parseInt(idvoy),source,destination ,Integer.parseInt(idclt), nom, cni, date,Integer.parseInt(prix));
            tdao.modifier(ti, id);
            viderTicket();
            liste_ticket();
        }
    }//GEN-LAST:event_btn_modifierActionPerformed
   private void liste_ticket() {
        TicketDAO tdao = new TicketDAO();
        List<Ticket> ticket = tdao.liste();
        for (int i = 0; i < ticket.size(); i++) {
            ((DefaultTableModel) tb_ticket.getModel()).addRow(new Object[]{
                ticket.get(i).getIdtkt(),
                ticket.get(i).getIdvoy(),
                ticket.get(i).getSource(),
                ticket.get(i).getDestination(),
                ticket.get(i).getIdclt(),
                ticket.get(i).getNom(),
                ticket.get(i).getCni(),
                ticket.get(i).getDate(),
                ticket.get(i).getPrix(),
        });
        }

    }
   private void combo_voyage() {
        VoyageDAO vdao = new VoyageDAO();
        List <Voyage> voyage = vdao.liste();
        for (int i = 0; i < voyage.size(); i++) {
           
           txt_voyage.addItem(voyage.get(i).getIdvoy()+"");
        }

    }
     private void combo_client() {
        ClientDAO cdao = new ClientDAO();
        List <Client> client = cdao.liste();
        
        
        for (int i = 0; i < client.size(); i++) {
           
           txt_client.addItem(client.get(i).getIdclt()+"");
           
        }
 
    }

    private void viderTicket() {
       
        txt_source.setText("");
        txt_destination.setText("");
        
        txt_nom.setText("");
        txt_cni.setText("");
        txt_date.setDate(null);
        DefaultTableModel model = (DefaultTableModel) tb_ticket.getModel();
        int n = model.getRowCount();
        for (int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
        }
    }
    private void btn_imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imprimerActionPerformed

    private void txt_prixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prixActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.Button btn_enregistrer;
    private com.raven.swing.Button btn_imprimer;
    private com.raven.swing.Button btn_modifier;
    private com.raven.swing.Button btn_supprimer;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JScrollPane jScrollPane10;
    private rojeru_san.complementos.RSTableMetro tb_ticket;
    private combo_suggestion.ComboBoxSuggestion txt_client;
    private textfield_suggestion.TextFieldSuggestion txt_cni;
    private com.toedter.calendar.JDateChooser txt_date;
    private textfield_suggestion.TextFieldSuggestion txt_destination;
    private textfield_suggestion.TextFieldSuggestion txt_nom;
    private textfield_suggestion.TextFieldSuggestion txt_prix;
    private textfield_suggestion.TextFieldSuggestion txt_source;
    private combo_suggestion.ComboBoxSuggestion txt_voyage;
    // End of variables declaration//GEN-END:variables
}
