/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import classe.Client;
import dao.ClientDAO;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author halid
 */
public class PanelClients extends javax.swing.JPanel {

    /**
     * Creates new form PanelClients
     */
    public PanelClients() {
        initComponents();
         viderClient();
         liste_client();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel20 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_date1 = new com.toedter.calendar.JDateChooser();
        jScrollPane7 = new javax.swing.JScrollPane();
        tb_client = new rojeru_san.complementos.RSTableMetro();
        txt_nom1 = new textfield_suggestion.TextFieldSuggestion();
        txt_prenom = new textfield_suggestion.TextFieldSuggestion();
        txt_tel = new textfield_suggestion.TextFieldSuggestion();
        txt_adresse = new textfield_suggestion.TextFieldSuggestion();
        txt_cni1 = new textfield_suggestion.TextFieldSuggestion();
        txt_genre = new combo_suggestion.ComboBoxSuggestion();
        btn_enregistrer1 = new com.raven.swing.Button();
        btn_supprimer1 = new com.raven.swing.Button();
        btn_modifier1 = new com.raven.swing.Button();
        btn_imprimer1 = new com.raven.swing.Button();
        jLabel34 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Nom");
        jPanel20.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 90, 40));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Prenom");
        jPanel20.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 110, 40));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Telephone");
        jPanel20.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 130, 40));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Gestion des Clients");
        jPanel20.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 320, 40));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Genre");
        jPanel20.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 80, 40));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("CNI");
        jPanel20.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 70, 40));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Date");
        jPanel20.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 70, 40));

        txt_date1.setBackground(new java.awt.Color(255, 255, 255));
        txt_date1.setDoubleBuffered(false);
        txt_date1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel20.add(txt_date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 440, 40));

        tb_client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nom", "Prenom", "Telephone", "Adresse", "Genre", "Cni", "Date"
            }
        ));
        tb_client.setColorBackgoundHead(new java.awt.Color(153, 153, 255));
        tb_client.setColorBordeFilas(new java.awt.Color(153, 153, 255));
        tb_client.setColorBordeHead(new java.awt.Color(153, 153, 255));
        tb_client.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tb_client.setColorFilasForeground1(new java.awt.Color(153, 153, 255));
        tb_client.setColorFilasForeground2(new java.awt.Color(153, 153, 255));
        tb_client.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        tb_client.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        tb_client.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        tb_client.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        tb_client.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        tb_client.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tb_client.setRowHeight(40);
        tb_client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_clientMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tb_client);

        jPanel20.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 1190, 470));

        txt_nom1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_nom1.setRound(0);
        txt_nom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nom1ActionPerformed(evt);
            }
        });
        jPanel20.add(txt_nom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 380, 40));

        txt_prenom.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_prenom.setRound(0);
        txt_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_prenomActionPerformed(evt);
            }
        });
        jPanel20.add(txt_prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 380, 40));

        txt_tel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_tel.setRound(0);
        txt_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telActionPerformed(evt);
            }
        });
        jPanel20.add(txt_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 380, 40));

        txt_adresse.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_adresse.setRound(0);
        txt_adresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_adresseActionPerformed(evt);
            }
        });
        jPanel20.add(txt_adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 440, 40));

        txt_cni1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_cni1.setRound(0);
        txt_cni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cni1ActionPerformed(evt);
            }
        });
        jPanel20.add(txt_cni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 440, 40));

        txt_genre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Homme", "Femme" }));
        txt_genre.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_genreActionPerformed(evt);
            }
        });
        jPanel20.add(txt_genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 440, 40));

        btn_enregistrer1.setBackground(new java.awt.Color(51, 51, 255));
        btn_enregistrer1.setForeground(new java.awt.Color(255, 255, 255));
        btn_enregistrer1.setText("Enregistrer");
        btn_enregistrer1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_enregistrer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrer1ActionPerformed(evt);
            }
        });
        jPanel20.add(btn_enregistrer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 150, 45));

        btn_supprimer1.setBackground(new java.awt.Color(255, 51, 51));
        btn_supprimer1.setForeground(new java.awt.Color(255, 255, 255));
        btn_supprimer1.setText("Supprimer");
        btn_supprimer1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_supprimer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimer1ActionPerformed(evt);
            }
        });
        jPanel20.add(btn_supprimer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 150, 45));

        btn_modifier1.setBackground(new java.awt.Color(255, 204, 51));
        btn_modifier1.setForeground(new java.awt.Color(255, 255, 255));
        btn_modifier1.setText("Modifier");
        btn_modifier1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_modifier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier1ActionPerformed(evt);
            }
        });
        jPanel20.add(btn_modifier1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 150, 45));

        btn_imprimer1.setBackground(new java.awt.Color(51, 204, 0));
        btn_imprimer1.setForeground(new java.awt.Color(255, 255, 255));
        btn_imprimer1.setText("Imprimer");
        btn_imprimer1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_imprimer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimer1ActionPerformed(evt);
            }
        });
        jPanel20.add(btn_imprimer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 400, 150, 45));

        jLabel34.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Adresse");
        jPanel20.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 100, 40));

        add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 3, 1260, 960));
    }// </editor-fold>//GEN-END:initComponents

    private void tb_clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_clientMouseClicked
        int index = tb_client.getSelectedRow();
        if (index!=-1){
            int id = (int)tb_client.getValueAt(index,0);
            ClientDAO edao = new ClientDAO();
            Client etu = edao.recherche(id);
            txt_nom1.setText(etu.getNom());
            txt_prenom.setText(etu.getPrenom());
            txt_tel.setText(etu.getTelephone());
            txt_adresse.setText(etu.getAdresse());
            txt_genre.setSelectedItem(etu.getGenre());
            txt_cni1.setText(etu.getCni());
            txt_date1.setDate(etu.getDateenrg());
        }
    }//GEN-LAST:event_tb_clientMouseClicked
 private void liste_client() {
        ClientDAO edao = new ClientDAO();
        List<Client> etudiant = edao.liste();
        for (int i = 0; i < etudiant.size(); i++) {
            ((DefaultTableModel) tb_client.getModel()).addRow(new Object[]{
                etudiant.get(i).getIdclt(),
                etudiant.get(i).getNom(),
                etudiant.get(i).getPrenom(),
                etudiant.get(i).getTelephone(),
                etudiant.get(i).getAdresse(),
                etudiant.get(i).getGenre(),
                etudiant.get(i).getCni(),
                etudiant.get(i).getDateenrg()
            });
        }

    }

    private void viderClient() {
        txt_nom1.setText("");
        txt_prenom.setText("");
        txt_tel.setText("");
        txt_adresse.setText("");
        txt_genre.setSelectedItem("");
        txt_cni1.setText("");
        txt_date1.setDate(null);
        DefaultTableModel model = (DefaultTableModel) tb_client.getModel();
        int n = model.getRowCount();
        for (int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
        }
    }



    private void txt_nom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nom1ActionPerformed

    private void txt_prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prenomActionPerformed

    private void txt_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telActionPerformed

    private void txt_adresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_adresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_adresseActionPerformed

    private void txt_cni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cni1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cni1ActionPerformed

    private void txt_genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_genreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_genreActionPerformed

    private void btn_enregistrer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrer1ActionPerformed
        ClientDAO edao = new ClientDAO();
        String nom = txt_nom1.getText();
        String prenom = txt_prenom.getText();
        String telephone = txt_tel.getText();
        String adresse = txt_adresse.getText();
        String genre = txt_genre.getSelectedItem().toString();
        String cni = txt_cni1.getText();
        Date date = txt_date1.getDate();
        if ( nom.equals("") || prenom.equals("") || telephone.equals("") || adresse.equals("") || genre.equals("") || cni.equals("")  ) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner tous les champs ");
        } else {
            Client et = new Client(nom, prenom, telephone, adresse, genre, cni, date);
            edao.inserer(et);
            viderClient();
            liste_client();
        }
    }//GEN-LAST:event_btn_enregistrer1ActionPerformed

    private void btn_supprimer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimer1ActionPerformed
        int index = tb_client.getSelectedRow();
        if (index==-1){
            JOptionPane.showMessageDialog(this,"Veuillez selectionnez une ligne");
        }
        else {
            int id = (int)tb_client.getValueAt(index,0);
            ClientDAO edao = new ClientDAO();
            edao.supprimer(id);
            viderClient();
            liste_client();

        }
    }//GEN-LAST:event_btn_supprimer1ActionPerformed

    private void btn_modifier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier1ActionPerformed
        ClientDAO edao = new ClientDAO();
        String nom = txt_nom1.getText();
        String prenom = txt_prenom.getText();
        String telephone = txt_tel.getText();
        String adresse = txt_adresse.getText();
        String genre = txt_genre.getSelectedItem().toString();
        String cni = txt_cni1.getText();
        Date date = txt_date1.getDate();
        if ( nom.equals("") || prenom.equals("") || telephone.equals("") || adresse.equals("") || genre.equals("") || cni.equals("")  ) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner tous les champs ");
        } else {
            int index = tb_client.getSelectedRow();
            int id = (int)tb_client.getValueAt(index,0);
            Client et = new Client(nom, prenom, telephone, adresse, genre, cni, date);
            edao.modifier(et, id);
            viderClient();
            liste_client();
        }
    }//GEN-LAST:event_btn_modifier1ActionPerformed

    private void btn_imprimer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imprimer1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.Button btn_enregistrer1;
    private com.raven.swing.Button btn_imprimer1;
    private com.raven.swing.Button btn_modifier1;
    private com.raven.swing.Button btn_supprimer1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JScrollPane jScrollPane7;
    private rojeru_san.complementos.RSTableMetro tb_client;
    private textfield_suggestion.TextFieldSuggestion txt_adresse;
    private textfield_suggestion.TextFieldSuggestion txt_cni1;
    private com.toedter.calendar.JDateChooser txt_date1;
    private combo_suggestion.ComboBoxSuggestion txt_genre;
    private textfield_suggestion.TextFieldSuggestion txt_nom1;
    private textfield_suggestion.TextFieldSuggestion txt_prenom;
    private textfield_suggestion.TextFieldSuggestion txt_tel;
    // End of variables declaration//GEN-END:variables
}
