/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import classe.Car;
import classe.Voyage;
import dao.CarDAO;
import dao.Connectdb;
import dao.VoyageDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author halid
 */
public class PanelCar extends javax.swing.JPanel {
boolean modifier;
    /**
     * Creates new form PanelVoyage
     */
    
    public PanelCar() {
        initComponents();
      
        viderCar();
        liste_car();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CarAjouter = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_taille = new combo_suggestion.ComboBoxSuggestion();
        txt_nb_place = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txt_marque = new textfield_suggestion.TextFieldSuggestion();
        jLabel38 = new javax.swing.JLabel();
        btn_enregistrer45 = new com.raven.swing.Button();
        btn_supprimer45 = new com.raven.swing.Button();
        jLabel40 = new javax.swing.JLabel();
        txt_matricule = new textfield_suggestion.TextFieldSuggestion();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tb_car = new rojeru_san.complementos.RSTableMetro();
        jLabel50 = new javax.swing.JLabel();
        btn_enregistrer3 = new com.raven.swing.Button();
        btn_supprimer3 = new com.raven.swing.Button();
        btn_modifier3 = new com.raven.swing.Button();
        btn_imprimer3 = new com.raven.swing.Button();

        CarAjouter.setUndecorated(true);
        CarAjouter.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fiche Voyage");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 50));

        CarAjouter.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_taille.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "100", "150", "200" }));
        txt_taille.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jPanel2.add(txt_taille, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 460, 40));

        txt_nb_place.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jPanel2.add(txt_nb_place, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 100, 30));

        jLabel37.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel37.setText("Taille");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        txt_marque.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_marque.setRound(0);
        txt_marque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_marqueActionPerformed(evt);
            }
        });
        jPanel2.add(txt_marque, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 460, 40));

        jLabel38.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel38.setText("Marque");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 30));

        btn_enregistrer45.setBackground(new java.awt.Color(51, 51, 255));
        btn_enregistrer45.setForeground(new java.awt.Color(255, 255, 255));
        btn_enregistrer45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/valid-vector-icon-png_267488.png"))); // NOI18N
        btn_enregistrer45.setText("  Terminer");
        btn_enregistrer45.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        btn_enregistrer45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrer45ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_enregistrer45, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 150, 45));

        btn_supprimer45.setBackground(new java.awt.Color(255, 51, 51));
        btn_supprimer45.setForeground(new java.awt.Color(255, 255, 255));
        btn_supprimer45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/anull-vector-icon-png_267488.png"))); // NOI18N
        btn_supprimer45.setText("  Annuler");
        btn_supprimer45.setToolTipText("");
        btn_supprimer45.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        btn_supprimer45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimer45ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_supprimer45, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 150, 45));

        jLabel40.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel40.setText("Matricule");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 30));

        txt_matricule.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        txt_matricule.setRound(0);
        txt_matricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matriculeActionPerformed(evt);
            }
        });
        jPanel2.add(txt_matricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 460, 40));

        CarAjouter.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 550, 480));

        setMinimumSize(new java.awt.Dimension(1240, 890));
        setPreferredSize(new java.awt.Dimension(1240, 890));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setMinimumSize(new java.awt.Dimension(1240, 890));
        jPanel19.setPreferredSize(new java.awt.Dimension(1240, 890));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_car.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Marque", "Matricule", "Taille", "Statut"
            }
        ));
        tb_car.setColorBackgoundHead(new java.awt.Color(153, 153, 255));
        tb_car.setColorBordeFilas(new java.awt.Color(153, 153, 255));
        tb_car.setColorBordeHead(new java.awt.Color(153, 153, 255));
        tb_car.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tb_car.setColorFilasForeground1(new java.awt.Color(153, 153, 255));
        tb_car.setColorFilasForeground2(new java.awt.Color(153, 153, 255));
        tb_car.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        tb_car.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        tb_car.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        tb_car.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        tb_car.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        tb_car.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tb_car.setRowHeight(40);
        tb_car.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_carMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(tb_car);

        jPanel19.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 1180, 740));

        jLabel50.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 51, 255));
        jLabel50.setText("Gestion des Cars");
        jPanel19.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        btn_enregistrer3.setBackground(new java.awt.Color(51, 51, 255));
        btn_enregistrer3.setForeground(new java.awt.Color(255, 255, 255));
        btn_enregistrer3.setText("Enregistrer");
        btn_enregistrer3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_enregistrer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrer3ActionPerformed(evt);
            }
        });
        jPanel19.add(btn_enregistrer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 150, 45));

        btn_supprimer3.setBackground(new java.awt.Color(255, 51, 51));
        btn_supprimer3.setForeground(new java.awt.Color(255, 255, 255));
        btn_supprimer3.setText("Supprimer");
        btn_supprimer3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_supprimer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimer3ActionPerformed(evt);
            }
        });
        jPanel19.add(btn_supprimer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 150, 45));

        btn_modifier3.setBackground(new java.awt.Color(255, 204, 51));
        btn_modifier3.setForeground(new java.awt.Color(255, 255, 255));
        btn_modifier3.setText("Modifier");
        btn_modifier3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_modifier3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier3ActionPerformed(evt);
            }
        });
        jPanel19.add(btn_modifier3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 150, 45));

        btn_imprimer3.setBackground(new java.awt.Color(51, 204, 0));
        btn_imprimer3.setForeground(new java.awt.Color(255, 255, 255));
        btn_imprimer3.setText("Imprimer");
        btn_imprimer3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btn_imprimer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimer3ActionPerformed(evt);
            }
        });
        jPanel19.add(btn_imprimer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, 150, 45));

        add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 890));
    }// </editor-fold>//GEN-END:initComponents

    private void tb_carMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_carMouseClicked
        int index = tb_car.getSelectedRow();
        if (index!=-1){
            int id = (int)tb_car.getValueAt(index,0);
            CarDAO edao = new CarDAO();
            Car etu = edao.recherche(id);
            txt_marque.setText(etu.getMarque());
            txt_matricule.setText(etu.getMatricule());
            txt_taille.setSelectedItem(etu.getNb_place()+"");
          
        }
    }//GEN-LAST:event_tb_carMouseClicked

    private void btn_enregistrer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrer3ActionPerformed
         CarAjouter.setVisible(true);
         modifier=false;
          CarAjouter.pack();
        CarAjouter.setLocationRelativeTo(null);
        CarAjouter.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       
        Statut_car();
        /* CarDAO edao = new CarDAO();
        String marque = txt_marque.getText();
        String nb_place = txt_taille.getSelectedItem().toString();
        if (marque.equals("") || nb_place.equals("")) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner tous les champs ");
        } else {
            Car et = new Car(marque,Integer.parseInt(nb_place));
            edao.inserer(et);
            viderCar();
            liste_car();
        }*/
    }//GEN-LAST:event_btn_enregistrer3ActionPerformed

    private void btn_supprimer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimer3ActionPerformed
        int index = tb_car.getSelectedRow();
         Statut_car();
        if (index==-1){
            JOptionPane.showMessageDialog(this,"Veuillez selectionnez une ligne");
        }
        else {
            int id = (int)tb_car.getValueAt(index,0);
            CarDAO edao = new CarDAO();
            edao.supprimer(id);
            viderCar();
            liste_car();

        }
    }//GEN-LAST:event_btn_supprimer3ActionPerformed

    private void btn_modifier3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier3ActionPerformed
        int index = tb_car.getSelectedRow();
         Statut_car();
        if (index==-1){
            JOptionPane.showMessageDialog(this,"Veuillez selectionnez un client");
        }
        else {
        
        CarAjouter.setVisible(true);
        modifier=true;
        int indexx = tb_car.getSelectedRow();
        if (indexx!=-1){
            int id = (int)tb_car.getValueAt(index,0);
            CarDAO edao = new CarDAO();
            Car etu = edao.recherche(id);
            txt_marque.setText(etu.getMarque());
            txt_matricule.setText(etu.getMatricule());
            txt_taille.setSelectedItem(etu.getNb_place()+"");
           
        
        }
        }
        /*        CarDAO edao = new CarDAO();
        String marque = txt_marque.getText();
        String nb_place = txt_taille.getSelectedItem().toString();
        if (marque.equals("") || nb_place.equals("")) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner tous les champs ");
        } else {
            int index = tb_car.getSelectedRow();
            int id = (int)tb_car.getValueAt(index,0);
            Car et = new Car(marque,Integer.parseInt(nb_place));
            edao.modifier(et, id);
            viderCar();
            liste_car();
        }*/
    }//GEN-LAST:event_btn_modifier3ActionPerformed
      private void liste_car() {
        Statut_car();
          CarDAO edao = new CarDAO();
        List<Car> etudiant = edao.liste();
        for (int i = 0; i < etudiant.size(); i++) {
            ((DefaultTableModel) tb_car.getModel()).addRow(new Object[]{
                etudiant.get(i).getIdcar(),
                etudiant.get(i).getMarque(),
                etudiant.get(i).getMatricule(),
                etudiant.get(i).getNb_place(),
                etudiant.get(i).getStatut()
              
            });
        }

    }
 public void Statut_car(){
      VoyageDAO vdao = new VoyageDAO();
        List<Voyage> voyage = vdao.liste();
         Date today = new Date();
        today.setHours(0);
        today.setMinutes(0);
        today.setSeconds(0);
         for (int i = 0; i < voyage.size(); i++) {
            
            //Voyage voy=vdao.recherche(voyage.get(i).getDepart());
            Date depart=voyage.get(i).getDepart();
            Date arrive=voyage.get(i).getArrive();
            
            if(depart.compareTo(today) < 0 && arrive.compareTo(today) > 0){
            
             try {
            Connection con = Connectdb.getInstance();
            String sql = "UPDATE car INNER JOIN voyage ON car.idcar = voyage.idcar SET car.statut='Indisponible' WHERE voyage.depart < DATE( NOW() ) and voyage.arrive >DATE( NOW() );";
            //String sql = "update issue_book_details set status = ? where student_id = ? and book_id = ? and status = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.executeUpdate();
           int rowCount =  pst.executeUpdate();
        } catch (SQLException e) {
        }
           }
            else if(arrive.compareTo(today) < 0){
                 try {
            Connection con = Connectdb.getInstance();
            String sql = "UPDATE car INNER JOIN voyage ON car.idcar = voyage.idcar SET car.statut='Disponible' WHERE  voyage.arrive <DATE( NOW() );";
            //String sql = "update issue_book_details set status = ? where student_id = ? and book_id = ? and status = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.executeUpdate();
           int rowCount =  pst.executeUpdate();
        } catch (SQLException e) {
        }
            }
             else if(depart.compareTo(today) > 0){
                 try {
            Connection con = Connectdb.getInstance();
            String sql = "UPDATE car INNER JOIN voyage ON car.idcar = voyage.idcar SET car.statut='Reserver' WHERE  voyage.depart >DATE( NOW() );";
            //String sql = "update issue_book_details set status = ? where student_id = ? and book_id = ? and status = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.executeUpdate();
           int rowCount =  pst.executeUpdate();
        } catch (SQLException e) {
        }
            }
          }
        
        
      
 }
    private void viderCar() {
        txt_marque.setText("");
        txt_taille.setSelectedItem("");
        txt_matricule.setText("");
        
       
        DefaultTableModel model = (DefaultTableModel) tb_car.getModel();
        int n = model.getRowCount();
        for (int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
        }
    }
    private void btn_imprimer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimer3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imprimer3ActionPerformed

    private void txt_marqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_marqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marqueActionPerformed

    private void btn_enregistrer45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrer45ActionPerformed
        CarDAO edao = new CarDAO();
        String marque = txt_marque.getText();
        String nb_place = txt_taille.getSelectedItem().toString();
        String matricule = txt_matricule.getText();
        String statut = "Disponible";
        if (marque.equals("") || nb_place.equals("")) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner tous les champs ");
        } else if(modifier==false){

            Car et = new Car(marque,matricule,Integer.parseInt(nb_place),statut);
            edao.inserer(et);
            viderCar();
            liste_car();
            CarAjouter.setVisible(false);
        }
        else if(modifier==true){
             int index = tb_car.getSelectedRow();
            int id = (int)tb_car.getValueAt(index,0);
            Car et = new Car(marque,matricule,Integer.parseInt(nb_place),statut);
            edao.modifier(et, id);
            viderCar();
            liste_car();
            CarAjouter.setVisible(false);
        }

        //VoyageAjouter.dispose();
    }//GEN-LAST:event_btn_enregistrer45ActionPerformed

    private void btn_supprimer45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimer45ActionPerformed
        CarAjouter.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_supprimer45ActionPerformed

    private void txt_matriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matriculeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame CarAjouter;
    private com.raven.swing.Button btn_enregistrer3;
    private com.raven.swing.Button btn_enregistrer45;
    private com.raven.swing.Button btn_imprimer3;
    private com.raven.swing.Button btn_modifier3;
    private com.raven.swing.Button btn_supprimer3;
    private com.raven.swing.Button btn_supprimer45;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane11;
    private rojeru_san.complementos.RSTableMetro tb_car;
    private textfield_suggestion.TextFieldSuggestion txt_marque;
    private textfield_suggestion.TextFieldSuggestion txt_matricule;
    private javax.swing.JLabel txt_nb_place;
    private combo_suggestion.ComboBoxSuggestion txt_taille;
    // End of variables declaration//GEN-END:variables
}
